server:
  port: 10000

spring:
  application:
    name: ticket-app
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${OIDC_CLIENT_ID}
            client-secret: ${OIDC_CLIENT_SECRET}
            scope:
              - openid
              - profile
            redirect-uri: https://web2-projekt1-7x55.onrender.com/login/oauth2/code/auth0
        provider:
          auth0:
            issuer-uri: https://dev-u2jdw0b2r78whx70.eu.auth0.com/
      resourceserver:
        jwt:
          issuer-uri: https://dev-u2jdw0b2r78whx70.eu.auth0.com/