server:
  port: 10000

spring:
  application:
    name: ticket-app
  datasource:
    url: jdbc:postgresql://dpg-cs60ohlumphs73b3pm60-a.frankfurt-postgres.render.com:5432/web2_projekt1_db
    username: web2_projekt1_db_user
    password: lhxKota5l3UDqEKDs4425Gw6QWf5Me6D
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: 7biWA41clcyfWuBsjuYCvxFKelsnk0sE
            client-secret: ZOQbrQt6W3p6z7fJ-doTuKiHiV0kjxlEmbxtaIcbFX2Z9VVvRR9GPjqdX8QHcEfs
            scope:
              - openid
              - profile
            redirect-uri: https://web2-projekt1-7x55.onrender.com/login/oauth2/code/auth0
        provider:
          auth0:
            issuer-uri: https://dev-u2jdw0b2r78whx70.eu.auth0.com/
      resourceserver:
        jwt:
          issuer-uri: https://dev-u2jdw0b2r78whx70.eu.auth0.com/